import mongoose from "mongoose";

/*
|--------------------------------------------------------------------------
| Notification Schema
|--------------------------------------------------------------------------
*/

const notificationSchema =
  new mongoose.Schema(
    {
      /*
      |--------------------------------------------------------------------------
      | Store
      |--------------------------------------------------------------------------
      |
      | null when notification is:
      | - All Stores
      | - Admins
      |
      | Mongo Store ObjectId when audience is:
      | - Store
      |
      */

      storeId: {
        type:
          mongoose.Schema.Types
            .ObjectId,

        ref: "Store",

        default: null,

        index: true,
      },

      /*
      |--------------------------------------------------------------------------
      | Notification Content
      |--------------------------------------------------------------------------
      */

      title: {
        type: String,

        required: [
          true,
          "Notification title is required.",
        ],

        trim: true,

        maxlength: [
          150,
          "Notification title cannot exceed 150 characters.",
        ],
      },

      message: {
        type: String,

        required: [
          true,
          "Notification message is required.",
        ],

        trim: true,

        maxlength: [
          2000,
          "Notification message cannot exceed 2000 characters.",
        ],
      },

      /*
      |--------------------------------------------------------------------------
      | Type
      |--------------------------------------------------------------------------
      */

      type: {
        type: String,

        enum: [
          "General",
          "Shift",
          "Issue",
          "Food Safety",
          "Maintenance",
          "Cash",
          "System",
        ],

        default: "General",

        index: true,
      },

      /*
      |--------------------------------------------------------------------------
      | Priority
      |--------------------------------------------------------------------------
      */

      priority: {
        type: String,

        enum: [
          "Low",
          "Medium",
          "High",
          "Critical",
        ],

        default: "Medium",

        index: true,
      },

      /*
      |--------------------------------------------------------------------------
      | Audience
      |--------------------------------------------------------------------------
      |
      | All Stores:
      |   Every store account can see it.
      |
      | Store:
      |   Only the selected store can see it.
      |
      | Admins:
      |   Only administrators can see it.
      |
      */

      audience: {
        type: String,

        enum: [
          "All Stores",
          "Store",
          "Admins",
        ],

        default: "Store",

        index: true,
      },

      /*
      |--------------------------------------------------------------------------
      | Notification Status
      |--------------------------------------------------------------------------
      |
      | This is NOT the read/unread status.
      |
      | Read state will eventually belong to each recipient separately.
      |--------------------------------------------------------------------------
      */

      status: {
        type: String,

        enum: [
          "Active",
          "Archived",
        ],

        default: "Active",

        index: true,
      },

      /*
      |--------------------------------------------------------------------------
      | Creator
      |--------------------------------------------------------------------------
      |
      | These fields must be generated by the backend from req.user.
      | The frontend should never be trusted to supply them.
      |--------------------------------------------------------------------------
      */

      createdByUid: {
        type: String,

        default: "",

        trim: true,
      },

      createdByName: {
        type: String,

        default: "",

        trim: true,

        maxlength: 150,
      },
    },

    {
      timestamps: true,

      versionKey: false,
    }
  );

/*
|--------------------------------------------------------------------------
| Validation
|--------------------------------------------------------------------------
|
| A notification with audience "Store" must have a Mongo Store ObjectId.
|--------------------------------------------------------------------------
*/

notificationSchema.pre(
  "validate",
  function (next) {
    if (
      this.audience ===
        "Store" &&
      !this.storeId
    ) {
      this.invalidate(
        "storeId",
        "Store is required for Store notifications."
      );
    }

    /*
    |--------------------------------------------------------------------------
    | Global/Admin Notification
    |--------------------------------------------------------------------------
    |
    | Prevent stale store references when changing audience.
    |--------------------------------------------------------------------------
    */

    if (
      this.audience ===
        "All Stores" ||
      this.audience ===
        "Admins"
    ) {
      this.storeId = null;
    }

    next();
  }
);

/*
|--------------------------------------------------------------------------
| Indexes
|--------------------------------------------------------------------------
*/

/*
| Latest notifications
*/

notificationSchema.index({
  createdAt: -1,
});

/*
| Store notification history
*/

notificationSchema.index({
  storeId: 1,
  createdAt: -1,
});

/*
| Audience notification history
*/

notificationSchema.index({
  audience: 1,
  status: 1,
  createdAt: -1,
});

/*
| Type / Priority filtering
*/

notificationSchema.index({
  type: 1,
  priority: 1,
  createdAt: -1,
});

/*
|--------------------------------------------------------------------------
| Model
|--------------------------------------------------------------------------
*/

const Notification =
  mongoose.models.Notification ||
  mongoose.model(
    "Notification",
    notificationSchema
  );

export default Notification;